### ISSUE TITLE
Illuminate\Broadcasting\BroadcastException 404 NOT FOUND

### ISSUE THREAD

**Issue by namsudtho** [AfikDeri/Messenger-App-VueJS-and-Laravel#1]
i follow all step as you (youtube ep02) but i have this error
![image](https://user-images.githubusercontent.com/15089720/44647301-e186c900-aa07-11e8-96cc-692a6a935d53.png)
my code:
NewMessage.php
`namespace App\Events;
use App\Message;
use Illuminate\Broadcasting\Channel;
use Illuminate\Queue\SerializesModels;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Broadcasting\PresenceChannel;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;

class NewMessage implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $message;

    public function __construct(Message $message)
    {
        $this->message = $message;
    }

    public function broadcastOn()
    {
        return new PrivateChannel('messages.' . $this->message->to);
    }

    public function broadcastWith()
    {        
        return ["message" => $this->message];
    }

}`

ContactsController.php
`namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\User;
use App\Message;
use App\Events\NewMessage;

class ContactsController extends Controller
{
    public function get()
    {
        $contacts = User::where('id', '!=', auth()->id())->get();
        return response()->json($contacts);
    }

    public function getMessagesFor($id)
    {
        $messages = Message::where('from', $id)->orWhere('to', $id)->get();
        return response()->json($messages);
    }

    public function send(Request $request)
    {
        $message = Message::create([
            'from' => auth()->id(),
            'to' => $request->contact_id,
            'text' => $request->text
        ]);
        broadcast(new NewMessage($message));
        return response()->json($message);
    }
}`

channels.php
`Broadcast::channel('messages.{id}', function ($user, $id) {
    return $user->id === (int) $id;
});`

**Comment by SaulFadal** [comment]
Same issue here ! 
I hope there is a solution.

**Comment by namsudtho** [comment]
@SaulFadal, **I solved the problem.** 
step 1 register website pusher.com
step 2 create new app on pusher.com
step 3 update PUSHER_APP_ID, PUSHER_APP_KEY and PUSHER_APP_SECRET on your project

**Comment by spinnovius** [comment]
http://localhost/contacts 404 (Not Found)

**Comment by anower00** [comment]
![test](https://user-images.githubusercontent.com/33565728/54075457-aecc6000-42c9-11e9-9f7a-34d808b69ef8.PNG)

how can i solve this problem

**Comment by AfikDeri** [comment]
@spinnovius & @anower00 , running laravel locally is not always an easy task and once you go to localhost it's not always serving your app correctly.
Try to either run it using `laravel valet`, `laravel homestead` or event `php artisan serve` and make sure that in your `.env` file you have the correct app url (sometimes you need to specify the port as well).

**Comment by HossainAbedy** [comment]
Hey guys,I had the same issue for several months and finally it worked for me.(php artisan config:cache)
When you update your .env file be sure to restart the server and clear the cache.All you have to follow the instruction provided above and thats it.

**Comment by AfikDeri** [comment]
Hi guys.
I'm trying to reproduce your error with no luck. I'm using Laravel Valet and I haven't tested it with Xamp or homestead or `php artisan serve`.
I pulled the latest master locally and following the setup steps it works great.
I can only suggest that you make sure you have the correct settings in you pusher app
![image](https://user-images.githubusercontent.com/17595033/64108972-fb7b8a00-cd86-11e9-97ab-d2a3f7699b71.png)

and that you have you .env file generated with all the necessary values
![image](https://user-images.githubusercontent.com/17595033/64109043-25cd4780-cd87-11e9-8e80-0e54cd1c2c8b.png)

Finally, if nothing works, try to pull the latest master branch again and follow the setup steps to make sure you didn't miss anything (there is a new step to seed the database to help with the initial setup).

If nothing works post your issue here and I'll do my best to help you guys.

**Comment by HossainAbedy** [comment]
Hi Afik,
I watched your tutorials several months ago and I followed your
instructions. It worked great. And I further developed it by adding many
additional features.
Since I got busy at my office , I couldn’t manage enough time for further
development of this particular app.

It would be really kind if you can check out my work at
https://github.com/HossainAbedy/AdvancedMessenger
and perheps provide some feedback or any ideas for adding any more
features.Provided,you can use my application as a reference for developing
your existing tutorial vide.

This application is based upon your original application.
Already grateful for your effort to teach us new. God bless you.

**Comment by rajshreevyas** [comment]
hello Afik,
I setup project at local after cloning from git.I want to implement the type indicator functionality in the project.but pusher debuger did not give error. I found that listenforwhisper function is not working, but .whisper() function works fine, pusher also received client typing event. 
Please help me in this issue to debug

 Echo.private(`messages.${this.user.id}`)
                 .whisper('typing',this.user);

 Echo.private(`messages.${this.user.id}`)
                .listenForWhisper('typing', (response) => {
                    console.log("listening for whisper");
                   console.log(response);
                });

**Comment by namsudtho** [comment]
I solved the problem.
step 1 register website pusher.com
step 2 create new app on pusher.com
step 3 update PUSHER_APP_ID, PUSHER_APP_KEY and PUSHER_APP_SECRET on your project
